Piranha path

diff --git a/Dockerfiles/piranha/Dockerfile b/Dockerfiles/piranha/Dockerfile
--- a/Dockerfiles/piranha/Dockerfile
+++ b/Dockerfiles/piranha/Dockerfile
@@ -54,14 +54,13 @@ RUN wget https://smithlabresearch.org/downloads/piranha-1.2.1.tar.gz \
     && cd piranha-1.2.1 \
     && ./configure --with-bam_tools_headers=/usr/local/include/bamtools \
                   --with-bam_tools_library=/usr/local/lib \
-    && make all \
+    && make \
     && make install \
+    && cd .. \
+    && rm -rf piranha-1.2.1.tar.gz
 
-# Add Piranha binary directory to PATH
-ENV PATH="/usr/local/bin:/opt/piranha-1.2.1/bin:${PATH}"
-
-# Create symlink to ensure Piranha is accessible
-RUN ln -sf /usr/local/bin/piranha /usr/local/bin/Piranha
+# Add Piranha to PATH
+ENV PATH="/usr/local/bin:${PATH}"
 
 # Install samtools
 RUN wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 \
@@ -73,10 +72,14 @@ RUN wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.
     && cd .. \
     && rm -rf samtools-1.21*
 
+# Create symlink after installation
+RUN if [ -f /usr/local/bin/piranha ]; then \
+        ln -sf /usr/local/bin/piranha /usr/local/bin/Piranha; \
+    fi
+
 # Verify installations
-RUN which Piranha && \
-    which samtools && \
-    Piranha --help
+RUN which piranha || echo "piranha not found" && \
+    which samtools || echo "samtools not found"
 
 # Set default working directory
 WORKDIR /data
